POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": null,
    "maximunAttendees": 1
}

###

POST http://localhost:3333/events/79cfed55-ba55-4178-b87c-db84d8dd0ca4/attendees
Content-Type: application/json

{
    "name": "Adriane",
    "email": "adriane@rocktseat.com.br"
}

###

GET http://localhost:3333/events/79cfed55-ba55-4178-b87c-db84d8dd0ca4

###

GET http://localhost:3333/attendees/2/badge

###


GET http://localhost:3333/attendees/2/check-in


###
GET http://localhost:3333/events/79cfed55-ba55-4178-b87c-db84d8dd0ca4/attendees?query=adriane